# ExternalSecret: w10/api/key → K8s Secret "api-secret" trong namespace demo
# Dùng SecretStore Access Key (namespace-scoped, cần aws-credentials secret)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secret
  namespace: demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-accesskey
    kind: SecretStore
  target:
    name: api-secret
    creationPolicy: Owner
  data:
  - secretKey: API_KEY
    remoteRef:
      key: w10/api/key
      property: API_KEY
