# ExternalSecret: w10/app/config → K8s Secret "app-config-secret" trong namespace demo
# Dùng SecretStore sealed secret (credentials được seal trong git)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-config-secret
  namespace: demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-sealedsecret
    kind: SecretStore
  target:
    name: app-config-secret
    creationPolicy: Owner
  data:
  - secretKey: APP_SECRET
    remoteRef:
      key: w10/app/config
      property: APP_SECRET
  - secretKey: APP_ENV
    remoteRef:
      key: w10/app/config
      property: APP_ENV
