---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-credentials-sealedsecret
  namespace: demo
spec:
  encryptedData:
    access-key-id: AgAfEVNI06I8ERn/xV/hPdPDJaQUisfgF2+v4WeVLyZKDHKUT4MnYBOKoWuZotZEqhryseN6UtNGVHlfNJ0Zyr4oKK2Fzea9nwTAS3Y/eaaKNOIibfEeRmMcwkVcyg1hCnTGm0Z93no1woG8gApjC0pKR1KCNBwnwIgyhJFCBSRqos6Zsf8W3tlfsmwRRSZRsmWOjdfxmwht+hk5bCIClxbyHh/9OhXEUoPl+4HTRcj55XDZpTD0v9gv4Ennc0Xeeot7xEricDbckYc6CJzB11YTeu56C6ZYmN+uhOT64L98G4fIjCRB6dgTBZ1raadNQsvVlX0byA8obenwZOR4QEACf+IFunqk2Jm5sf7WpcnMBXrDLr7d5n3XR1JvUrxGvWwhVL/HACbQRRi4/h16yD293NzvaUcedRa/7lA9gObpA0HKujLi2ae93cd/mZTm68yAZCk5HY/RF9qeD6z5ar+lFnNG7rCqT5yp8K2xkvFWn6BEffn8l2rQIpg2X2aywerSHDRI7aumTm4z/HNDcltcqjlfvF17BsqaMv8pW+hk/SHyX96uZ/tUTpxdswJqN0I8MaEyLGKoHM6rs6u4GfZ6HeNeE2GG7S+VvdGaYaOnNms4gXgv533RiMzRDcWl6x0KM1MIuHJLaBzb9bRL6rgaZ3CXAd7SNk/3eAspQmuz8aJiUV7R7jnfBEyXh82xHpjOqLSnbWxu6tU2nrxR8gClw96nnQ==
    secret-access-key: AgAYBBqpTQveJykenz6fkf9peBw8FGFh+xAR8zrVm+uirCTcRPZSNWwxfcJV+hNbiiT7Sa0bifiheXONmHslRLCusSFL4XBEiH/u3xVdJSHlf+A5RRT4vAfYrs9FsVV6b/4CrnLg2NCo/Yfcaq+SnloYSIbJf/7NJSBdPl/zGsMI5UKEgW7/G6zNOf/AccPREJHmNNHE/7UFOIfxW9vPNeylsOCnV1CueNmLBZ/PAE1MrPzLNOryBl6BdCMlnZEh9wwKT1C+P7x42lXVHeimcI1+uEPEIsdNHK/Y6chGHhMIamTmR43KDi9mCZRX0X5aBt2MDVPrPcg5G1u/JZNrFY7ECzUdEWgGakQpP53S4p5A3YCGSo0F4PC9cbwBzTmbtvoajB1jv2S81ekztjWIwzaIDw87odUD3rlDGvgFUw66/URCNR3Z//qQi9qFDrYii59GmFJ2LrKx2KVM6vKt158CT5KDN6NBoUr008d9n9gO7lNMkaYzKskt+Py4oJGMBhwAHLizUIt/VaYoe73iHTQ5SNCU4aZHRci8qMidI8ebI3yHtY/Z3HI7/AhEL1FrcX6SKmsaeobQvx9fFZ97/JQa1HdF1UWrOBCf6wN50jMLCIXo8DFDgu0spgI8zEHPwUAMB/joc6YO5YotMciX0XzQYvWxyrQLkn+QKbeiilCMGhlhm3o0FCg7w6qpGo8DngdwLNSxY6CwegObq37ntvcNDNZjm/ZY0NbQvz7V1NRooS6/+zZhEIu7
  template:
    metadata:
      name: aws-credentials-sealedsecret
      namespace: demo
