# Auth 3: Static Access Key được lưu bằng Sealed Secrets (an toàn commit lên git)
# Sealed Secrets controller giải mã SealedSecret → K8s Secret "aws-credentials-sealedsecret"
# SecretStore này reference Secret đó để authenticate với AWS
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager-sealedsecret
  namespace: demo
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials-sealedsecret
            key: access-key-id
            namespace: demo
          secretAccessKeySecretRef:
            name: aws-credentials-sealedsecret
            key: secret-access-key
            namespace: demo
