# ArgoCD App: ESO - Auth via Static Access Key
# SecretStore + ExternalSecret cho w10/api/key
# Yêu cầu: tạo K8s Secret "aws-credentials" trong namespace demo TRƯỚC khi sync
#   kubectl apply -f app-eso-accesskey/aws-credentials.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-accesskey
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/Vuong-Bach/temp.git
    path: app-eso-accesskey
    targetRevision: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
